services:
  postgres:
    image: postgres:16
    container_name: gym_postgres
    environment:
      POSTGRES_DB: gymdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports: 
      - "5434:5432"  # Evita conflito com 5432 local
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    
volumes:
  postgres_data: